//首页控制器
app.controller('indexController',function($scope,loginService){
    //登录后显示用户名
    $scope.showName=function(){
        loginService.showName().success(
            function(response){
                $scope.loginName=response.loginName;
            }
        );
    }
});